runtime: nodejs20
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 1
env_variables:
  NODE_ENV: "production"
  # CRITICAL: You must provide a CLOUD MongoDB URI (e.g., MongoDB Atlas). 
  # Localhost (127.0.0.1) will NOT work on Google Cloud.
  MONGODB_URI: "mongodb+srv://pratapadhikari37_db_user:z2vwqFzKNDO2FYVG@cluster0.joilie5.mongodb.net/?appName=Cluster0"
  EMAIL_USER: "jekamobilerepair@gmail.com"
  EMAIL_PASS: "qwcq yrvd rivk oqsb"
  # Set your desired admin password here
  ADMIN_PASSWORD: "admin"
